"""Playlist-related wiring."""

from app.wiring_utils import bind_map


def bind_playlist(TidalApp, seen=None):
    from app.app_playlist import (
        on_playlist_sort_clicked,
        on_playlist_folder_card_clicked,
        on_playlist_folder_up_clicked,
        on_create_playlist_folder_clicked,
        on_playlist_folder_rename_clicked,
        on_playlist_folder_delete_clicked,
        on_playlist_card_clicked,
        on_remote_playlist_card_clicked,
        _refresh_remote_playlist_visibility_button,
        on_remote_playlist_toggle_public_clicked,
        _open_cloud_playlist_editor,
        on_remote_playlist_rename_clicked,
        on_remote_playlist_delete_clicked,
        on_remote_playlist_move_to_folder_clicked,
        on_remove_single_track_from_remote_playlist,
        on_playlist_track_selected,
        _next_playlist_name,
        on_create_playlist_clicked,
        _prompt_playlist_pick,
        on_add_tracks_to_playlist,
        on_add_single_track_to_playlist,
        on_add_current_album_to_playlist,
        _prompt_playlist_name,
        on_playlist_start_inline_rename,
        on_playlist_commit_inline_rename,
        on_playlist_cancel_inline_rename,
        on_playlist_delete_clicked,
        on_playlist_remove_track_clicked,
        on_playlist_move_track_clicked,
        on_playlist_toggle_edit,
        on_playlist_reorder_track,
    )

    bind_map(TidalApp, [
        ("on_playlist_sort_clicked", on_playlist_sort_clicked),
        ("on_playlist_folder_card_clicked", on_playlist_folder_card_clicked),
        ("on_playlist_folder_up_clicked", on_playlist_folder_up_clicked),
        ("on_create_playlist_folder_clicked", on_create_playlist_folder_clicked),
        ("on_playlist_folder_rename_clicked", on_playlist_folder_rename_clicked),
        ("on_playlist_folder_delete_clicked", on_playlist_folder_delete_clicked),
        ("on_playlist_card_clicked", on_playlist_card_clicked),
        ("on_remote_playlist_card_clicked", on_remote_playlist_card_clicked),
        ("_refresh_remote_playlist_visibility_button", _refresh_remote_playlist_visibility_button),
        ("on_remote_playlist_toggle_public_clicked", on_remote_playlist_toggle_public_clicked),
        ("_open_cloud_playlist_editor", _open_cloud_playlist_editor),
        ("on_remote_playlist_rename_clicked", on_remote_playlist_rename_clicked),
        ("on_remote_playlist_delete_clicked", on_remote_playlist_delete_clicked),
        ("on_remote_playlist_move_to_folder_clicked", on_remote_playlist_move_to_folder_clicked),
        ("on_remove_single_track_from_remote_playlist", on_remove_single_track_from_remote_playlist),
        ("on_playlist_track_selected", on_playlist_track_selected),
        ("_next_playlist_name", _next_playlist_name),
        ("on_create_playlist_clicked", on_create_playlist_clicked),
        ("_prompt_playlist_pick", _prompt_playlist_pick),
        ("on_add_tracks_to_playlist", on_add_tracks_to_playlist),
        ("on_add_single_track_to_playlist", on_add_single_track_to_playlist),
        ("on_add_current_album_to_playlist", on_add_current_album_to_playlist),
        ("_prompt_playlist_name", _prompt_playlist_name),
        ("on_playlist_start_inline_rename", on_playlist_start_inline_rename),
        ("on_playlist_commit_inline_rename", on_playlist_commit_inline_rename),
        ("on_playlist_cancel_inline_rename", on_playlist_cancel_inline_rename),
        ("on_playlist_delete_clicked", on_playlist_delete_clicked),
        ("on_playlist_remove_track_clicked", on_playlist_remove_track_clicked),
        ("on_playlist_move_track_clicked", on_playlist_move_track_clicked),
        ("on_playlist_toggle_edit", on_playlist_toggle_edit),
        ("on_playlist_reorder_track", on_playlist_reorder_track),
    ], seen=seen)
