"""Handler-related wiring."""

from app.wiring_utils import bind_map


def bind_handlers_core(TidalApp, seen=None):
    from app.app_handlers import (
        on_about_clicked,
        on_login_clicked,
        on_logout_clicked,
        on_settings_clicked,
        on_volume_changed_ui,
        on_tech_info_clicked,
        on_toggle_mode,
        on_fav_clicked,
        on_artist_fav_clicked,
        on_login_success,
        _get_active_queue,
        _set_play_queue,
        _is_queue_nav_selected,
        _sync_queue_handle_state,
        toggle_queue_drawer,
        close_queue_drawer,
        get_sorted_playlist_tracks,
        _toggle_login_view,
        _set_login_view_pending,
        _set_overlay_handles_visible,
        _show_login_method_dialog,
        _start_login_flow,
        _open_login_url,
        _cleanup_login_dialog,
        _cancel_login_attempt,
        _build_qr_tempfile,
        _show_login_qr_dialog,
        _on_login_success_for_attempt,
        _on_login_failed,
        _on_login_failed_for_attempt,
    )

    bind_map(TidalApp, [
        ("on_about_clicked", on_about_clicked),
        ("on_login_clicked", on_login_clicked),
        ("on_logout_clicked", on_logout_clicked),
        ("on_settings_clicked", on_settings_clicked),
        ("on_volume_changed_ui", on_volume_changed_ui),
        ("on_tech_info_clicked", on_tech_info_clicked),
        ("on_toggle_mode", on_toggle_mode),
        ("on_fav_clicked", on_fav_clicked),
        ("on_artist_fav_clicked", on_artist_fav_clicked),
        ("on_login_success", on_login_success),
        ("_get_active_queue", _get_active_queue),
        ("_set_play_queue", _set_play_queue),
        ("_is_queue_nav_selected", _is_queue_nav_selected),
        ("_sync_queue_handle_state", _sync_queue_handle_state),
        ("toggle_queue_drawer", toggle_queue_drawer),
        ("close_queue_drawer", close_queue_drawer),
        ("get_sorted_playlist_tracks", get_sorted_playlist_tracks),
        ("_toggle_login_view", _toggle_login_view),
        ("_set_login_view_pending", _set_login_view_pending),
        ("_set_overlay_handles_visible", _set_overlay_handles_visible),
        ("_show_login_method_dialog", _show_login_method_dialog),
        ("_start_login_flow", _start_login_flow),
        ("_open_login_url", _open_login_url),
        ("_cleanup_login_dialog", _cleanup_login_dialog),
        ("_cancel_login_attempt", _cancel_login_attempt),
        ("_build_qr_tempfile", _build_qr_tempfile),
        ("_show_login_qr_dialog", _show_login_qr_dialog),
        ("_on_login_success_for_attempt", _on_login_success_for_attempt),
        ("_on_login_failed", _on_login_failed),
        ("_on_login_failed_for_attempt", _on_login_failed_for_attempt),
    ], seen=seen)


def bind_handlers_extra(TidalApp, seen=None):
    from app.app_handlers import (
        _generate_shuffle_list,
        refresh_liked_songs_dashboard,
        on_queue_track_selected,
        _refresh_queue_views,
        on_queue_remove_track_clicked,
        on_queue_clear_clicked,
        on_history_album_clicked,
        on_history_track_clicked,
        _debug_dump_button_metrics,
        build_daily_mixes,
        render_daily_mixes,
        on_daily_mix_track_selected,
        on_daily_mix_item_activated,
    )

    bind_map(TidalApp, [
        ("_generate_shuffle_list", _generate_shuffle_list),
        ("refresh_liked_songs_dashboard", refresh_liked_songs_dashboard),
        ("on_queue_track_selected", on_queue_track_selected),
        ("_refresh_queue_views", _refresh_queue_views),
        ("on_queue_remove_track_clicked", on_queue_remove_track_clicked),
        ("on_queue_clear_clicked", on_queue_clear_clicked),
        ("on_history_album_clicked", on_history_album_clicked),
        ("on_history_track_clicked", on_history_track_clicked),
        ("_debug_dump_button_metrics", _debug_dump_button_metrics),
        ("build_daily_mixes", build_daily_mixes),
        ("render_daily_mixes", render_daily_mixes),
        ("on_daily_mix_track_selected", on_daily_mix_track_selected),
        ("on_daily_mix_item_activated", on_daily_mix_item_activated),
    ], seen=seen)
