"""Visualizer-related wiring."""

from app.wiring_utils import bind_map


def bind_visualizer(TidalApp, seen=None):
    from app.app_visualizer import (
        _apply_overlay_scroll_padding,
        _ensure_overlay_handles_visible,
        _viz_sync_key,
        _get_viz_offset_from_latency_profile,
        _apply_viz_sync_offset_for_device,
        on_viz_sync_offset_update,
        _drop_down_names,
        _selected_name_from_dropdown,
        _build_visualizer_for_backend,
        _resolve_viz_backend_key,
        _sync_viz_dropdown_models,
        _rebuild_visualizer_backend,
        on_viz_bars_changed,
        _apply_viz_bars_by_count,
        _apply_spectrum_theme_by_index,
        _apply_viz_effect_by_index,
        on_viz_effect_changed,
        _apply_viz_profile_by_index,
        on_viz_profile_changed,
        on_spectrum_theme_changed,
        on_viz_page_changed,
        _sync_viz_tab_runtime_state,
        _should_enable_spectrum_stream,
        _sync_spectrum_stream_state,
        _start_spectrum_stream_prewarm,
        _apply_viz_panel_theme,
        on_spectrum_data,
        _apply_viz_frame,
        _stop_viz_placeholder,
        _start_viz_placeholder_if_needed,
        _blend_spectrum_frames,
        _schedule_viz_handle_realign,
        toggle_visualizer,
        _set_visualizer_expanded,
        _set_viz_content_opacity,
        _start_viz_fade_in,
        _position_viz_handle,
        _start_viz_handle_follow_transition,
        _align_viz_handle_to_play_button,
        _animate_viz_handle_to,
    )

    bind_map(TidalApp, [
        ("_apply_overlay_scroll_padding", _apply_overlay_scroll_padding),
        ("_ensure_overlay_handles_visible", _ensure_overlay_handles_visible),
        ("_viz_sync_key", _viz_sync_key),
        ("_get_viz_offset_from_latency_profile", _get_viz_offset_from_latency_profile),
        ("_apply_viz_sync_offset_for_device", _apply_viz_sync_offset_for_device),
        ("on_viz_sync_offset_update", on_viz_sync_offset_update),
        ("_drop_down_names", _drop_down_names),
        ("_selected_name_from_dropdown", _selected_name_from_dropdown),
        ("_build_visualizer_for_backend", _build_visualizer_for_backend),
        ("_resolve_viz_backend_key", _resolve_viz_backend_key),
        ("_sync_viz_dropdown_models", _sync_viz_dropdown_models),
        ("_rebuild_visualizer_backend", _rebuild_visualizer_backend),
        ("on_viz_bars_changed", on_viz_bars_changed),
        ("_apply_viz_bars_by_count", _apply_viz_bars_by_count),
        ("_apply_spectrum_theme_by_index", _apply_spectrum_theme_by_index),
        ("_apply_viz_effect_by_index", _apply_viz_effect_by_index),
        ("on_viz_effect_changed", on_viz_effect_changed),
        ("_apply_viz_profile_by_index", _apply_viz_profile_by_index),
        ("on_viz_profile_changed", on_viz_profile_changed),
        ("on_spectrum_theme_changed", on_spectrum_theme_changed),
        ("on_viz_page_changed", on_viz_page_changed),
        ("_sync_viz_tab_runtime_state", _sync_viz_tab_runtime_state),
        ("_should_enable_spectrum_stream", _should_enable_spectrum_stream),
        ("_sync_spectrum_stream_state", _sync_spectrum_stream_state),
        ("_start_spectrum_stream_prewarm", _start_spectrum_stream_prewarm),
        ("_apply_viz_panel_theme", _apply_viz_panel_theme),
        ("on_spectrum_data", on_spectrum_data),
        ("_apply_viz_frame", _apply_viz_frame),
        ("_stop_viz_placeholder", _stop_viz_placeholder),
        ("_start_viz_placeholder_if_needed", _start_viz_placeholder_if_needed),
        ("_blend_spectrum_frames", _blend_spectrum_frames),
        ("_schedule_viz_handle_realign", _schedule_viz_handle_realign),
        ("toggle_visualizer", toggle_visualizer),
        ("_set_visualizer_expanded", _set_visualizer_expanded),
        ("_set_viz_content_opacity", _set_viz_content_opacity),
        ("_start_viz_fade_in", _start_viz_fade_in),
        ("_position_viz_handle", _position_viz_handle),
        ("_start_viz_handle_follow_transition", _start_viz_handle_follow_transition),
        ("_align_viz_handle_to_play_button", _align_viz_handle_to_play_button),
        ("_animate_viz_handle_to", _animate_viz_handle_to),
    ], seen=seen)


def bind_lyrics_settings(TidalApp, seen=None):
    from app.app_visualizer import (
        _apply_lyrics_font_preset_by_index,
        on_lyrics_font_preset_changed,
        _apply_lyrics_motion_by_index,
        on_lyrics_motion_changed,
        _apply_lyrics_offset_ms,
        on_lyrics_offset_step,
    )

    bind_map(TidalApp, [
        ("_apply_lyrics_font_preset_by_index", _apply_lyrics_font_preset_by_index),
        ("on_lyrics_font_preset_changed", on_lyrics_font_preset_changed),
        ("_apply_lyrics_motion_by_index", _apply_lyrics_motion_by_index),
        ("on_lyrics_motion_changed", on_lyrics_motion_changed),
        ("_apply_lyrics_offset_ms", _apply_lyrics_offset_ms),
        ("on_lyrics_offset_step", on_lyrics_offset_step),
    ], seen=seen)
